version: '3.8'

services:
  airflow-postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - green_ml_net

  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: version
    entrypoint: >
      /bin/bash -c " airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com "
    networks:
      - green_ml_net

  airflow-webserver:
    image: apache/airflow:2.7.1
    restart: always
    user: root # [New]
    privileged: true # [New]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock # DockerOperator 필수
    command: webserver
    networks:
      - green_ml_net

  airflow-scheduler:
    image: apache/airflow:2.7.1
    user: root # [New]
    privileged: true # [New]
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock # DockerOperator 필수
    command: scheduler
    networks:
      - green_ml_net

networks:
  green_ml_net:
    external: true
    name: docker_green_ml_net
