version: '3.8'

services:
  # 1. 메타데이터 저장소 (PostgreSQL DB) - 실험 파라미터, 점수 등을 저장
  db:
    image: postgres:15
    container_name: mlflow_db
    restart: always
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - green_ml_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mlflow_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. 아티팩트 저장소 (MinIO) - 모델 파일(.pth), 로그 파일(.csv) 등 대용량 파일 저장
  minio:
    image: minio/minio
    container_name: mlflow_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API 포트 (MLflow 서버가 통신용)
      - "9001:9001" # 콘솔 포트 (사람이 웹으로 접속용)
    volumes:
      - minio_data:/data
    networks:
      - green_ml_net

  # 3. MLflow 트래킹 서버 - 우리가 접속해서 실험 결과를 보는 웹사이트
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    restart: always
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio_admin
      AWS_SECRET_ACCESS_KEY: minio_password
    command: >
      mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_password@db:5432/mlflow_db --default-artifact-root s3://mlflow-bucket/ --host 0.0.0.0 --port 5000
    networks:
      - green_ml_net

  # 4. API Server - 모델 서빙
  api-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: fraud_api_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - green_ml_net
    depends_on:
      - mlflow

networks:
  green_ml_net:
    driver: bridge

volumes:
  db_data:
  minio_data:
